group: travis_latest
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: SlZkKHPaYEeUHfypZIE6oVsr8fwnH7m9X8yEUc/mjGI66Khjm0CgySzLprmG2Jcc9w2g+/HK8XGgBrDpUQfbjPMflr4yBv97GiiRhUUu6ZbfyUa6phoGdDedHMsRzSwNzUk5BL23Z/wU6I3V0u2dxwGvU5bBXnZh0pJ9f+w5+ymTddHtbN3Tv37qAF63cPRBSF7UIBOWJoCv0PzNc1csbydXUQF4GJpiGy50m92hjmdyp9oKhEZ2zDUsHM/QWPwVi52jayUT6aH0lDQClq8uRNTi9rVIWHj/fa5THc5V62fSWRCbtpi7op6PrJWd/gvthDdGN/1gXzyYaCLKfRRmbFm3/tdoG7nlzqTqKAyB5oh3rM7LA2Iv5LTs89OBFddEmEHU2qFdr2xtC+9FreXIdK1u+QFRBeQLs1h9pbMcyo9dLfbqWIsk60H+xqL9YMbBysBEM/Tfrh7PQKn3ZnDZjqMZwgBwq6oiFLUpjYwfWZurfIojQENQ5f98qZpv6ddBBEBqy05IbXG/pMY4GGeoXqjlBgzxbj0/dMDnuZ3R8IqJjEBvMi8PNKk87LkWFXXg3oEnUhTBhBtPzuVfz8vFPCF/aJ9EU8cDX7E+eZYp5d0pGQ97sLG1w4uAJwJIYcPXzp3RLh5DO3SO40WcUD9A+jjAa8WUy1b8GvkYzTnZcYU=
  - secure: 3tmgC7zZiO2+1UNg9nwu3Q0CkvvI/12JvFY67bfrlFpk1fx4g/zATmKvJHUKH3fcX/On+QsDxCdBSDqmKc7/sxCcZhMWTO4nLObuCD9LjFqimwxGvY5vYHjVgD7fr72bxPOT/I1YC0vxH8eOMWOfhyKP0c5zkooKi7cvqeOTm80h2GJUWbtT21yE6RCewjikGSSQzu5IX9lK5pNnVe3D9neLfFDf5l77+izJ9ZoBujRASRUkxHmSMxXtyDcbMbT4jt5rLIBkvAx1blKg6I8s/54X5BL8QtjTMfkZX3ZVq0v9PiCGr6oZZF2omV54tLBdGar0XFfuWMRZbSKzTTmQLj5/i5PcaY0tTsN8/UgQXlyfvCmPk0eSx7xzcJuEPjbYrp4stQMlprcQHRjRDP2sozNGBFSLc9G/FddzExF9CSV/4gVWlI2f+3e2h1IW4v1HWk1WblTuTVFVPe6IeEPfOl7vqs5Yizr7HsL48eBGtxylNT+02I0QfHB2Ym0XZjvzY3/PzHWR/A6F1Bsz+8ov0j++32c/dbSZz0Ii7ePrSSC/H1K9ect/Occ/4Fj7xOrGXbXLzEUk6JH7FrA0hqkj/kKua61w78Z6ak6C8t2oCPYPe5V6kuYOiCbpKh3KHblqvs/L7iZAMSIqmjPONC41efGm9cic0kcoPMCcNrlwric=
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
