dist: trusty
sudo: false
language: node_js
node_js: node
cache: yarn


env:
  global:
  - secure: DqVa8Yng5emfov/9V/eytmZhFrWP7k9xHSwvWD8NqA+njO27d6YJjNAZYUng3pTbFZXBg1yREk1WLAODw6HfreUhUYq9II0Xj4GCZiU/6e1gSLyQ+gRt3bpXjR6Z7dOxGOpcU1j5BAHUH6ViGPKuby4R+OJdL3yEt+GSQG7gkkd6dX7GMDlwHV67VhXOBikV2cfHrtVolm8vKGsc/1XXw2tB0CDucMGCBzp2/pA3CHpq5HX/I9aeiEoG0l2yRVcgQXdUwD4xlahSlrDq2m+OvLckhwGZdTO7SVRs/7RlWcSFsiQHIHaofEyDSoIVo5oGebbnvznB+h2CU3a28f12XIPDh6PQSe7gxwqwFnJ0a/6IsjUw+3RlvD9A7186rDTh3KE1K9uvustNSK4InaxIbgK2wBlc88SCUJbFRN16SVUeU/cGg4QNVNMaPlpA+urevEuKTTgAVRT05WmigYce93NRLxN21Jvxq9Plwfjp4Qi4CYhrQ9U4ThWrwXbWkkIKs/myK+O5OBbtsa4krAsKUi0Y9R1KJiiW3jLw30P9r6+d+mO4oGj6M9Kzi+ZgeTcKxfmVcJh69niN4UVIXKply6d0vcpZ3oJEY3XzPrWbLbrPsR/+N3vNu/q8qF1Kn0lnhvczwyGOBHLPqWHg4dGHk8Ei3g+idqoeEl/WdRbaYP8=


before_install:
- openssl aes-256-cbc -K $encrypted_4bfa00ed87db_key -iv $encrypted_4bfa00ed87db_iv -in keys.tgz.enc -out keys.tgz -d
- tar -xf keys.tgz
- mv keys/* "${HOME}/.ssh"

- curl -LO https://github.com/github/hub/releases/download/v2.2.9/hub-linux-amd64-2.2.9.tgz
- tar -xf hub-linux-amd64-2.2.9.tgz
- export PATH="${PWD}/hub-linux-amd64-2.2.9/bin:${PATH}"

- rvm use --install $(bash <(curl -s https://vinsonchuong.github.io/scripts/rubyversion))
- gem install travis


deploy:
  provider: npm
  skip_cleanup: true
  api_key:
    secure: had2Y5HAqHuYtJwdxH1y6RYDfzIw7Nx6YGCbU3dVeoFVPKUeT/aPWNftnsku6Y9Br6Io0fmWc4PGkdfqZ9q4ZAws8RYeaqfA0QW27sr31Rren4edWywR5xF2haRWjxfRqy11qd4i+lU/HgjVZZDZsPX4dctszI2X7ZpUCaNwp+v8Jiboom3IYlcD6oTRIuXVTWCZ7ibD+hBAdZmbRvIMq7qpzsTdqtIK/jkdMnNEdIcopij47g8ps3NPGIkgiIIfa8k01xGvfx1bmCTfTZBEoV2Yv74PQN2p/vE31ch7O2+yHZg5B9jMvhfn0GRvL3Qv22KeLxQj1PJh/ILU63NKG5gr6M4io4qR6lDfKThQa6JSxwtPpekwt/7f1WW7I8FK7DbWj8KKE00h9car+XCq+HE14xr0qITk8CU6CZkwrOekpthemRHaCaymnQmbDpjgWzOMUbNgPnFw0Zm1LFjli22j+x7+CG2cSy776E7HYoHXXxwICvwilCy+WAALcryRk8BkTv8TRpIX1Sb6vMkSzPohlWkb1I5ZO20dS/4SC/Ee1klX/P9OgYY0iw4VDYM0QqXLyVkgxeyuVCTe6gcW9pkq0wiCDQZrfI1Sg/a5/B6ElUH2DmW9kOoMVyJsO4jVywJOkobJ7DOAfWZAi/7x6G6q8uepZjX0W580NJ/auyo=
  on:
    tags: true
  email:
    secure: qGY5ojdtqfzf0WLfTRRXd6Em3rAZPUVvkNoJci9G8llJQS2JU6YxTOVkwxTZZYU01RHkFVY23HA5AZ5lzq4bfQDC5UYE6HmRZfDrJeT3uILxzTLDswIwDJi2qR7hdshk3dIHiBfb/PrNbDluv6TT7Fm39NPUNOLAGxhE3/BRUrgkQd3hhhDOAMq+lQDTKQSWzQ88T4ApqvXCnyz3/xokhYVkH7AVQP4mSKftMjH7YiXnQW++Jm6MaN7TiT1AU36uF6ykAj358Oc5qUcgkyopII3GIzXtxKmdcWVi2Eb49ASEgmlvbAeRUdSJghTlpOvVQYx8+Raku5lts16zVP7w/PHjks/W/NqGPdT0/NVfKgllXQ/TS3H2Hlttspw+mkBgoEjNeBnBqyDMCJ5TnU0Kaz+jvu79SWmxmLqRrRYL6mkzTqEHcX3tcobfwT4JBGYmuNUtMuri+GLZR4nco6e274OGg8faHhzwhYlNE2InZT+Mf78iL9oGPWktkkXR/HiSUwzmfyctelHg61CjGnwu+RkStTVvNxkcpEYV0QhZrX4uX6IERXD42VSQNksYapekp9vbK4q1cNzbf6J7DynPgMu/8rG+jqoGisFbtx81NA+Y34/wcK9nO0q0kCJNAzxMdLULS12DNifFSDCasURb522eWY8CrfcefIa6X1Km/4E=
