language: node_js
node_js: node
cache: yarn
deploy:
  provider: npm
  api_key:
    secure: had2Y5HAqHuYtJwdxH1y6RYDfzIw7Nx6YGCbU3dVeoFVPKUeT/aPWNftnsku6Y9Br6Io0fmWc4PGkdfqZ9q4ZAws8RYeaqfA0QW27sr31Rren4edWywR5xF2haRWjxfRqy11qd4i+lU/HgjVZZDZsPX4dctszI2X7ZpUCaNwp+v8Jiboom3IYlcD6oTRIuXVTWCZ7ibD+hBAdZmbRvIMq7qpzsTdqtIK/jkdMnNEdIcopij47g8ps3NPGIkgiIIfa8k01xGvfx1bmCTfTZBEoV2Yv74PQN2p/vE31ch7O2+yHZg5B9jMvhfn0GRvL3Qv22KeLxQj1PJh/ILU63NKG5gr6M4io4qR6lDfKThQa6JSxwtPpekwt/7f1WW7I8FK7DbWj8KKE00h9car+XCq+HE14xr0qITk8CU6CZkwrOekpthemRHaCaymnQmbDpjgWzOMUbNgPnFw0Zm1LFjli22j+x7+CG2cSy776E7HYoHXXxwICvwilCy+WAALcryRk8BkTv8TRpIX1Sb6vMkSzPohlWkb1I5ZO20dS/4SC/Ee1klX/P9OgYY0iw4VDYM0QqXLyVkgxeyuVCTe6gcW9pkq0wiCDQZrfI1Sg/a5/B6ElUH2DmW9kOoMVyJsO4jVywJOkobJ7DOAfWZAi/7x6G6q8uepZjX0W580NJ/auyo=
  on:
    tags: true
