dist: trusty
sudo: false
language: node_js
node_js: node
cache: yarn
deploy:
  provider: npm
  api_key:
    secure: had2Y5HAqHuYtJwdxH1y6RYDfzIw7Nx6YGCbU3dVeoFVPKUeT/aPWNftnsku6Y9Br6Io0fmWc4PGkdfqZ9q4ZAws8RYeaqfA0QW27sr31Rren4edWywR5xF2haRWjxfRqy11qd4i+lU/HgjVZZDZsPX4dctszI2X7ZpUCaNwp+v8Jiboom3IYlcD6oTRIuXVTWCZ7ibD+hBAdZmbRvIMq7qpzsTdqtIK/jkdMnNEdIcopij47g8ps3NPGIkgiIIfa8k01xGvfx1bmCTfTZBEoV2Yv74PQN2p/vE31ch7O2+yHZg5B9jMvhfn0GRvL3Qv22KeLxQj1PJh/ILU63NKG5gr6M4io4qR6lDfKThQa6JSxwtPpekwt/7f1WW7I8FK7DbWj8KKE00h9car+XCq+HE14xr0qITk8CU6CZkwrOekpthemRHaCaymnQmbDpjgWzOMUbNgPnFw0Zm1LFjli22j+x7+CG2cSy776E7HYoHXXxwICvwilCy+WAALcryRk8BkTv8TRpIX1Sb6vMkSzPohlWkb1I5ZO20dS/4SC/Ee1klX/P9OgYY0iw4VDYM0QqXLyVkgxeyuVCTe6gcW9pkq0wiCDQZrfI1Sg/a5/B6ElUH2DmW9kOoMVyJsO4jVywJOkobJ7DOAfWZAi/7x6G6q8uepZjX0W580NJ/auyo=
  on:
    tags: true
  email:
    secure: qGY5ojdtqfzf0WLfTRRXd6Em3rAZPUVvkNoJci9G8llJQS2JU6YxTOVkwxTZZYU01RHkFVY23HA5AZ5lzq4bfQDC5UYE6HmRZfDrJeT3uILxzTLDswIwDJi2qR7hdshk3dIHiBfb/PrNbDluv6TT7Fm39NPUNOLAGxhE3/BRUrgkQd3hhhDOAMq+lQDTKQSWzQ88T4ApqvXCnyz3/xokhYVkH7AVQP4mSKftMjH7YiXnQW++Jm6MaN7TiT1AU36uF6ykAj358Oc5qUcgkyopII3GIzXtxKmdcWVi2Eb49ASEgmlvbAeRUdSJghTlpOvVQYx8+Raku5lts16zVP7w/PHjks/W/NqGPdT0/NVfKgllXQ/TS3H2Hlttspw+mkBgoEjNeBnBqyDMCJ5TnU0Kaz+jvu79SWmxmLqRrRYL6mkzTqEHcX3tcobfwT4JBGYmuNUtMuri+GLZR4nco6e274OGg8faHhzwhYlNE2InZT+Mf78iL9oGPWktkkXR/HiSUwzmfyctelHg61CjGnwu+RkStTVvNxkcpEYV0QhZrX4uX6IERXD42VSQNksYapekp9vbK4q1cNzbf6J7DynPgMu/8rG+jqoGisFbtx81NA+Y34/wcK9nO0q0kCJNAzxMdLULS12DNifFSDCasURb522eWY8CrfcefIa6X1Km/4E=
