/* @flow */
export { default as commitChanges } from './commitChanges'
export { default as createGitHubRepository } from './createGitHubRepository'
export { default as enableTravis } from './enableTravis'
export { default as encryptForTravis } from './encryptForTravis'
export { default as getAuthor } from './getAuthor'
export { default as getAuthorEmail } from './getAuthorEmail'
export { default as getAuthorName } from './getAuthorName'
export { default as getGitHubRepositoryName } from './getGitHubRepositoryName'
export { default as getNpmToken } from './getNpmToken'
export { default as getTravisApiKey } from './getTravisApiKey'
export { default as installPackages } from './installPackages'
export { default as writeTemplates } from './writeTemplates'
