name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
    - run: yarn
    - run: git config --global user.name 'John Doe'
    - run: git config --global user.email 'jdoe@example.com'
    - run: yarn test
      env:
        GITHUB_TOKEN: ${{ secrets.PRIVILEGED_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - if: github.ref == 'refs/heads/master'
      run: yarn release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
